<a href="https://colab.research.google.com/github/keshav123333/Pytorch_beginners/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

#intitalised

In [ ]:
t=torch.tensor([[1,2,3]])

In [ ]:
shape=(2,3)
one=torch.ones(shape)
zero=torch.zeros(shape)
rand=torch.randn(shape)

In [ ]:
#mimick the already tensor

rand1=torch.rand_like(t,dtype=torch.float)

In [ ]:
# .shape
# .device
# .dtype
# this three is main

In [ ]:
#require grad true means hai ki ab track kar iss param ko ye train karunga aage jaake mein

xdata=torch.tensor([[1,2]])
w=torch.tensor([[1,2],[3,4]],requires_grad=True,dtype=torch.float)

In [ ]:
# a*b if a b tensor so ye same size ke honge and element wise mul
# a@b now matrix mul hoga

# chapter 2

In [ ]:
score=torch.randn((2,3))
print(score)

tensor([[ 1.3163, -0.4209,  1.0861],
        [ 0.3507,  0.1674, -1.1606]])


In [ ]:
# if

print(score.mean())
print(score.mean(dim=0)) # row waise
print(score.mean(dim=1))


tensor(0.2231)
tensor([ 0.8335, -0.1268, -0.0373])
tensor([ 0.6605, -0.2142])


In [ ]:
# indexing

pop=torch.arange(start=2,end=10,)
print(pop.reshape(2,4))

tensor([[2, 3, 4, 5],
        [6, 7, 8, 9]])


In [ ]:
#Dyanamic selection

score=torch.tensor(
    # first row
    [[1,2,3,4,5],
    [32,4,21,34,32]]
)
print(torch.argmax(score,dim=1))

tensor([4, 3])


In [ ]:
# Selecting rows elemtn
tf=torch.randn((4,5))
print(tf)
index_to_gather=torch.tensor([[1],[0],[4]])
print(torch.gather(tf,dim=1,index=index_to_gather))
# so sun like ab tu index slect kar raha hai col wise
# 0 th row -> 1 index ka elemet
# 1 row -> 0  elemnt
# 2 row -> 4 element select

tensor([[ 0.3917,  0.6508,  0.4632, -0.4163,  1.0778],
        [-0.0881, -0.0622, -0.7071,  1.2828,  1.5120],
        [-0.1460,  1.2031, -0.5512, -0.8130,  0.9445],
        [ 1.0208,  0.1293, -0.6089,  0.1472, -0.5298]])
tensor([[ 0.6508],
        [-0.0881],
        [ 0.9445]])


#chapter 3
train a model

In [ ]:
N=10
D_in=1
D_out=1

X=torch.randn(N,D_in)

true_W=torch.tensor([[2.0]])
true_b=torch.tensor(3.0)
ytrue=X@true_W+true_b+torch.randn(N,D_out)*0.1

In [ ]:
ytrue

tensor([[ 2.8306],
        [ 0.6516],
        [-1.0569],
        [ 5.6377],
        [ 3.8923],
        [ 3.3857],
        [ 4.7013],
        [ 4.6934],
        [ 3.7904],
        [ 4.7439]])

In [ ]:
W=torch.randn((D_in,D_out),requires_grad=True)
b=torch.randn(1,requires_grad=True)
print(W)
print(ytrue@W+b)

tensor([[-1.5958]], requires_grad=True)
tensor([[ -5.6169],
        [ -2.1398],
        [  0.5866],
        [-10.0966],
        [ -7.3113],
        [ -6.5028],
        [ -8.6023],
        [ -8.5897],
        [ -7.1486],
        [ -8.6703]], grad_fn=<AddBackward0>)


In [ ]:
ypred=ytrue@W+b

error=ypred-ytrue
squared_error=error**2
loss=squared_error.mean()
print(loss)

tensor(120.5755, grad_fn=<MeanBackward0>)


In [ ]:
loss.backward()

In [ ]:
lr,epochs=0.01,100

W,b=torch.randn(1,1,requires_grad=True),torch.randn(1,requires_grad=True)

for epoch in range(epochs):
  #Forward pass and loss
  y_hat=X@W+b
  loss=torch.mean((y_hat-ytrue)**2)

  loss.backward()

  with torch.no_grad():
    W-=lr*W.grad
    b-=lr*b.grad

  if epoch%10==0:
    print(f"Epoch {epoch }, Loss : {loss.item():.4f}, W : {W.item()}, b : {b.item()}")
  W.grad.zero_();
  b.grad.zero_();

Epoch 0, Loss : 14.4171, W : -0.3971729576587677, b : 0.499076247215271
Epoch 10, Loss : 9.1872, W : 0.08408865332603455, b : 1.0204517841339111
Epoch 20, Loss : 5.8563, W : 0.46912646293640137, b : 1.4356441497802734
Epoch 30, Loss : 3.7349, W : 0.7772236466407776, b : 1.7662376165390015
Epoch 40, Loss : 2.3837, W : 1.023792028427124, b : 2.029435634613037
Epoch 50, Loss : 1.5231, W : 1.2211507558822632, b : 2.238948106765747
Epoch 60, Loss : 0.9749, W : 1.3791475296020508, b : 2.405700922012329
Epoch 70, Loss : 0.6258, W : 1.5056545734405518, b : 2.538400411605835
Epoch 80, Loss : 0.4033, W : 1.6069666147232056, b : 2.6439828872680664
Epoch 90, Loss : 0.2616, W : 1.688117504119873, b : 2.7279751300811768


In [ ]:
ypred1=X@W+b

In [ ]:
ypred1

tensor([[ 2.5853],
        [ 0.7274],
        [-0.7786],
        [ 5.0256],
        [ 3.4774],
        [ 3.0747],
        [ 4.3565],
        [ 3.9768],
        [ 3.5704],
        [ 4.2480]], grad_fn=<AddBackward0>)

#NN.Linear

In [ ]:
D_in=1
D_out=1

linear_layer=torch.nn.Linear(in_features=D_in,out_features=D_out)

print(linear_layer.weight)
print(linear_layer.bias)
y_hat=linear_layer(X)

print(y_hat[:,:])

Parameter containing:
tensor([[0.2149]], requires_grad=True)
Parameter containing:
tensor([-0.4316], requires_grad=True)
tensor([[-0.4566],
        [-0.6852],
        [-0.8704],
        [-0.1565],
        [-0.3469],
        [-0.3964],
        [-0.2388],
        [-0.2855],
        [-0.3355],
        [-0.2521]], grad_fn=<AliasBackward0>)


Activation function

In [ ]:
#relu
relu=torch.nn.ReLU()
sample_data=torch.tensor([-2.0,-0.5,0.0,0.5,2.0])
activated_data=relu(sample_data)
print(activated_data)

tensor([0.0000, 0.0000, 0.0000, 0.5000, 2.0000])


In [ ]:
#gelu
gelu=torch.nn.GELU()
sample_data=torch.tensor([-2.0,-0.5,0.0,0.5,2.0])
print(gelu(sample_data))

tensor([-0.0455, -0.1543,  0.0000,  0.3457,  1.9545])


In [ ]:
softmax=torch.nn.Softmax(dim=-1)
logits=torch.tensor([[1.0,2.0,4.0,5.0],[2.0,90,3,21]])
prob=softmax(logits)
print(prob)

tensor([[1.2755e-02, 3.4671e-02, 2.5619e-01, 6.9639e-01],
        [6.0546e-39, 1.0000e+00, 1.6458e-38, 1.0806e-30]])


In [ ]:
 #Embbeding

vocab_size=300
word_vector=10

emb=torch.nn.Embedding(num_embeddings=vocab_size,embedding_dim=word_vector)
input=torch.tensor([[10,31,44],[12,34,57]])
print(emb(input))

tensor([[[ 0.5107,  1.5185,  0.2516,  0.4048,  0.9013, -1.0815, -0.4634,
          -0.4039,  1.6142, -0.0824],
         [ 0.2489, -0.3665, -0.8776, -0.0845, -1.4855,  0.7970, -0.1872,
           0.4158, -2.0574, -0.3821],
         [ 0.7809, -0.0237, -0.3639, -0.1104,  1.3716, -0.0949, -1.0695,
           1.0487, -0.3196,  1.7325]],

        [[ 1.3323,  0.5375,  0.1768, -0.5053,  1.0203,  0.2184, -1.5145,
           1.9159, -0.1851, -0.4636],
         [ 0.2146,  1.6759, -0.7331, -1.0278,  1.6356,  0.4333,  0.2252,
           0.8408,  1.3092,  0.0360],
         [ 1.4211, -0.8028,  0.5530, -0.2017, -0.5429, -0.2085, -0.7388,
           0.1496,  0.1659,  0.2792]]], grad_fn=<EmbeddingBackward0>)


In [ ]:
#layer norm

norm_layer=torch.nn.LayerNorm(normalized_shape=3)
input_feature=torch.tensor([[[1.0,2.0,3.0],[4.0,5.0,6.0]]])
norm=norm_layer(input_feature)
print(norm.mean(dim=-1))
print(norm.std(dim=-1))

tensor([[0., 0.]], grad_fn=<MeanBackward1>)
tensor([[1.2247, 1.2247]], grad_fn=<StdBackward0>)


In [ ]:
#nn drpout
ui=torch.nn.Dropout(p=0.5)
input=torch.ones((1,10))
ui.train() #it activate the dropout
print(ui(input))


#yaha pe train roka as dropout onluactivate when train hoti
ui.eval()

print(ui(input))

tensor([[2., 2., 2., 0., 0., 2., 2., 0., 2., 2.]])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


best model to train

In [ ]:
class Linear_layer(torch.nn.Module):
  def __init__(self,inp,out):
    super().__init__()
    self.linear=torch.nn.Linear(in_features=inp,out_features=out)

  def forward(self,x):
    return self.linear(x)

In [ ]:
model=Linear_layer(inp=1,out=1)
print(model.linear.weight)
print(model.linear.bias)

Parameter containing:
tensor([[0.9351]], requires_grad=True)
Parameter containing:
tensor([0.2000], requires_grad=True)


In [ ]:
import torch.optim as optim

lr=0.01

optimizer=optim.Adam()

In [ ]:
epochs=100
for epoch in range(epochs):
  y_hat=model(X)
  loss=

100